"""
模块: migrations.versions.8359347629d1_delivery_content
职责: 为 delivery 增加 content 列，使无报告的推送也能补投递
依赖: 无
"""

"""delivery content

Revision ID: 8359347629d1
Revises: c0fbe5601730
Create Date: 2026-10-09 15:21:09.795226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8359347629d1'
down_revision: Union[str, Sequence[str], None] = 'c0fbe5601730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
